// Generated by Bisonc++ V4.09.02 on Wed, 17 Jan 2018 18:02:55 +0100

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {309, 4}, // 1: start ->  kezdes deklaraciok utasitasok befejezes
     {310, 2}, // 2: kezdes (PROGRAM) ->  PROGRAM AZONOSITO
     {311, 1}, // 3: befejezes (PROGRAM_VEGE) ->  PROGRAM_VEGE
     {312, 0}, // 4: deklaraciok ->  <empty>
     {312, 2}, // 5: deklaraciok (VALTOZOK) ->  VALTOZOK valtozolista
     {313, 1}, // 6: valtozolista ->  deklaracio
     {313, 2}, // 7: valtozolista ->  deklaracio valtozolista
     {314, 2}, // 8: deklaracio (EGESZ) ->  EGESZ AZONOSITO
     {314, 2}, // 9: deklaracio (LOGIKAI) ->  LOGIKAI AZONOSITO
     {314, 2}, // 10: deklaracio (IDO) ->  IDO AZONOSITO
     {315, 3}, // 11: utasitasok (UTASITASOK) ->  UTASITASOK utasitas utasitaslista
     {316, 0}, // 12: utasitaslista ->  <empty>
     {316, 2}, // 13: utasitaslista ->  utasitas utasitaslista
     {317, 1}, // 14: utasitas (SKIP) ->  SKIP
     {317, 1}, // 15: utasitas ->  ertekadas
     {317, 1}, // 16: utasitas ->  be
     {317, 1}, // 17: utasitas ->  ki
     {317, 1}, // 18: utasitas ->  elagazas
     {317, 1}, // 19: utasitas ->  ciklus
     {318, 3}, // 20: ertekadas (AZONOSITO) ->  AZONOSITO ERTEKADAS kifejezes
     {319, 2}, // 21: be (BE) ->  BE AZONOSITO
     {320, 2}, // 22: ki (KI) ->  KI kifejezes
     {321, 5}, // 23: elagazas (HA) ->  HA kifejezes AKKOR utasitaslista HA_VEGE
     {321, 7}, // 24: elagazas (HA) ->  HA kifejezes AKKOR utasitaslista KULONBEN utasitaslista HA_VEGE
     {322, 5}, // 25: ciklus (CIKLUS) ->  CIKLUS AMIG kifejezes utasitaslista CIKLUS_VEGE
     {323, 1}, // 26: kifejezes (SZAMKONSTANS) ->  SZAMKONSTANS
     {323, 1}, // 27: kifejezes (IGAZ) ->  IGAZ
     {323, 1}, // 28: kifejezes (HAMIS) ->  HAMIS
     {323, 1}, // 29: kifejezes (IDOKONST) ->  IDOKONST
     {323, 1}, // 30: kifejezes (AZONOSITO) ->  AZONOSITO
     {323, 4}, // 31: kifejezes (ORA) ->  ORA BALZAROJEL kifejezes JOBBZAROJEL
     {323, 4}, // 32: kifejezes (PERC) ->  PERC BALZAROJEL kifejezes JOBBZAROJEL
     {323, 3}, // 33: kifejezes (PLUSZ) ->  kifejezes PLUSZ kifejezes
     {323, 3}, // 34: kifejezes (MINUSZ) ->  kifejezes MINUSZ kifejezes
     {323, 3}, // 35: kifejezes (SZORZAS) ->  kifejezes SZORZAS kifejezes
     {323, 3}, // 36: kifejezes (OSZTAS) ->  kifejezes OSZTAS kifejezes
     {323, 3}, // 37: kifejezes (MARADEK) ->  kifejezes MARADEK kifejezes
     {323, 3}, // 38: kifejezes (KISEBB) ->  kifejezes KISEBB kifejezes
     {323, 3}, // 39: kifejezes (NAGYOBB) ->  kifejezes NAGYOBB kifejezes
     {323, 3}, // 40: kifejezes (EGYENLO) ->  kifejezes EGYENLO kifejezes
     {323, 3}, // 41: kifejezes (ES) ->  kifejezes ES kifejezes
     {323, 3}, // 42: kifejezes (VAGY) ->  kifejezes VAGY kifejezes
     {323, 2}, // 43: kifejezes (NEM) ->  NEM kifejezes
     {323, 3}, // 44: kifejezes (BALZAROJEL) ->  BALZAROJEL kifejezes JOBBZAROJEL
     {324, 1}, // 45: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 4} },           
    { {       309}, { 1} }, // start  
    { {       310}, { 2} }, // kezdes 
    { {       258}, { 3} }, // PROGRAM
    { {         0}, { 0} },           
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, {  3} },               
    { {     312}, {  4} }, // deklaraciok
    { {     259}, {  5} }, // VALTOZOK   
    { {       0}, { -4} },               
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, { 2} },             
    { {       276}, { 6} }, // AZONOSITO
    { {         0}, { 0} },             
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, { 3} },              
    { {       315}, { 7} }, // utasitasok
    { {       260}, { 8} }, // UTASITASOK
    { {         0}, { 0} },              
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       313}, {  9} }, // valtozolista
    { {       314}, { 10} }, // deklaracio  
    { {       271}, { 11} }, // EGESZ       
    { {       272}, { 12} }, // LOGIKAI     
    { {       281}, { 13} }, // IDO         
    { {         0}, {  0} },                
};

SR__ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  3} },                
    { {       311}, { 14} }, // befejezes   
    { {       261}, { 15} }, // PROGRAM_VEGE
    { {         0}, {  0} },                
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, { 13} },             
    { {       317}, { 16} }, // utasitas 
    { {       279}, { 17} }, // SKIP     
    { {       318}, { 18} }, // ertekadas
    { {       319}, { 19} }, // be       
    { {       320}, { 20} }, // ki       
    { {       321}, { 21} }, // elagazas 
    { {       322}, { 22} }, // ciklus   
    { {       276}, { 23} }, // AZONOSITO
    { {       269}, { 24} }, // BE       
    { {       270}, { 25} }, // KI       
    { {       262}, { 26} }, // HA       
    { {       266}, { 27} }, // CIKLUS   
    { {         0}, {  0} },             
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_10[] =
{
    { { REQ_DEF}, {  6} },                
    { {     313}, { 28} }, // valtozolista
    { {     314}, { 10} }, // deklaracio  
    { {     271}, { 11} }, // EGESZ       
    { {     272}, { 12} }, // LOGIKAI     
    { {     281}, { 13} }, // IDO         
    { {       0}, { -6} },                
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       276}, { 29} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       276}, { 30} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       276}, { 31} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_14[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_15[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_16[] =
{
    { { REQ_DEF}, {  14} },                 
    { {     316}, {  32} }, // utasitaslista
    { {     317}, {  33} }, // utasitas     
    { {     279}, {  17} }, // SKIP         
    { {     318}, {  18} }, // ertekadas    
    { {     319}, {  19} }, // be           
    { {     320}, {  20} }, // ki           
    { {     321}, {  21} }, // elagazas     
    { {     322}, {  22} }, // ciklus       
    { {     276}, {  23} }, // AZONOSITO    
    { {     269}, {  24} }, // BE           
    { {     270}, {  25} }, // KI           
    { {     262}, {  26} }, // HA           
    { {     266}, {  27} }, // CIKLUS       
    { {       0}, { -12} },                 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       273}, { 34} }, // ERTEKADAS
    { {         0}, {  0} },             
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       276}, { 35} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 36} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 46} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       267}, { 47} }, // AMIG
    { {         0}, {  0} },        
};

SR__ s_28[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_29[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_30[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_32[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_33[] =
{
    { { REQ_DEF}, {  14} },                 
    { {     316}, {  48} }, // utasitaslista
    { {     317}, {  33} }, // utasitas     
    { {     279}, {  17} }, // SKIP         
    { {     318}, {  18} }, // ertekadas    
    { {     319}, {  19} }, // be           
    { {     320}, {  20} }, // ki           
    { {     321}, {  21} }, // elagazas     
    { {     322}, {  22} }, // ciklus       
    { {     276}, {  23} }, // AZONOSITO    
    { {     269}, {  24} }, // BE           
    { {     270}, {  25} }, // KI           
    { {     262}, {  26} }, // HA           
    { {     266}, {  27} }, // CIKLUS       
    { {       0}, { -12} },                 
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 49} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_36[] =
{
    { { REQ_DEF}, {  11} },           
    { {     290}, {  50} }, // PLUSZ  
    { {     291}, {  51} }, // MINUSZ 
    { {     292}, {  52} }, // SZORZAS
    { {     293}, {  53} }, // OSZTAS 
    { {     294}, {  54} }, // MARADEK
    { {     288}, {  55} }, // KISEBB 
    { {     289}, {  56} }, // NAGYOBB
    { {     287}, {  57} }, // EGYENLO
    { {     285}, {  58} }, // ES     
    { {     284}, {  59} }, // VAGY   
    { {       0}, { -22} },           
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       274}, { 60} }, // BALZAROJEL
    { {         0}, {  0} },              
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       274}, { 61} }, // BALZAROJEL
    { {         0}, {  0} },              
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 62} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 63} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       263}, { 64} }, // AKKOR  
    { {       290}, { 50} }, // PLUSZ  
    { {       291}, { 51} }, // MINUSZ 
    { {       292}, { 52} }, // SZORZAS
    { {       293}, { 53} }, // OSZTAS 
    { {       294}, { 54} }, // MARADEK
    { {       288}, { 55} }, // KISEBB 
    { {       289}, { 56} }, // NAGYOBB
    { {       287}, { 57} }, // EGYENLO
    { {       285}, { 58} }, // ES     
    { {       284}, { 59} }, // VAGY   
    { {         0}, {  0} },           
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 65} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_49[] =
{
    { { REQ_DEF}, {  11} },           
    { {     290}, {  50} }, // PLUSZ  
    { {     291}, {  51} }, // MINUSZ 
    { {     292}, {  52} }, // SZORZAS
    { {     293}, {  53} }, // OSZTAS 
    { {     294}, {  54} }, // MARADEK
    { {     288}, {  55} }, // KISEBB 
    { {     289}, {  56} }, // NAGYOBB
    { {     287}, {  57} }, // EGYENLO
    { {     285}, {  58} }, // ES     
    { {     284}, {  59} }, // VAGY   
    { {       0}, { -20} },           
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 66} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 67} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 68} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 69} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 70} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 71} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 72} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 73} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 74} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 75} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 76} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       323}, { 77} }, // kifejezes   
    { {       257}, { 37} }, // SZAMKONSTANS
    { {       277}, { 38} }, // IGAZ        
    { {       278}, { 39} }, // HAMIS       
    { {       280}, { 40} }, // IDOKONST    
    { {       276}, { 41} }, // AZONOSITO   
    { {       283}, { 42} }, // ORA         
    { {       282}, { 43} }, // PERC        
    { {       286}, { 44} }, // NEM         
    { {       274}, { 45} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_62[] =
{
    { { REQ_DEF}, {   9} },           
    { {     290}, {  50} }, // PLUSZ  
    { {     291}, {  51} }, // MINUSZ 
    { {     292}, {  52} }, // SZORZAS
    { {     293}, {  53} }, // OSZTAS 
    { {     294}, {  54} }, // MARADEK
    { {     288}, {  55} }, // KISEBB 
    { {     289}, {  56} }, // NAGYOBB
    { {     287}, {  57} }, // EGYENLO
    { {       0}, { -43} },           
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, { 12} },               
    { {       275}, { 78} }, // JOBBZAROJEL
    { {       290}, { 50} }, // PLUSZ      
    { {       291}, { 51} }, // MINUSZ     
    { {       292}, { 52} }, // SZORZAS    
    { {       293}, { 53} }, // OSZTAS     
    { {       294}, { 54} }, // MARADEK    
    { {       288}, { 55} }, // KISEBB     
    { {       289}, { 56} }, // NAGYOBB    
    { {       287}, { 57} }, // EGYENLO    
    { {       285}, { 58} }, // ES         
    { {       284}, { 59} }, // VAGY       
    { {         0}, {  0} },               
};

SR__ s_64[] =
{
    { { REQ_DEF}, {  14} },                 
    { {     316}, {  79} }, // utasitaslista
    { {     317}, {  33} }, // utasitas     
    { {     279}, {  17} }, // SKIP         
    { {     318}, {  18} }, // ertekadas    
    { {     319}, {  19} }, // be           
    { {     320}, {  20} }, // ki           
    { {     321}, {  21} }, // elagazas     
    { {     322}, {  22} }, // ciklus       
    { {     276}, {  23} }, // AZONOSITO    
    { {     269}, {  24} }, // BE           
    { {     270}, {  25} }, // KI           
    { {     262}, {  26} }, // HA           
    { {     266}, {  27} }, // CIKLUS       
    { {       0}, { -12} },                 
};

SR__ s_65[] =
{
    { { REQ_DEF}, {  24} },                 
    { {     316}, {  80} }, // utasitaslista
    { {     290}, {  50} }, // PLUSZ        
    { {     291}, {  51} }, // MINUSZ       
    { {     292}, {  52} }, // SZORZAS      
    { {     293}, {  53} }, // OSZTAS       
    { {     294}, {  54} }, // MARADEK      
    { {     288}, {  55} }, // KISEBB       
    { {     289}, {  56} }, // NAGYOBB      
    { {     287}, {  57} }, // EGYENLO      
    { {     285}, {  58} }, // ES           
    { {     284}, {  59} }, // VAGY         
    { {     317}, {  33} }, // utasitas     
    { {     279}, {  17} }, // SKIP         
    { {     318}, {  18} }, // ertekadas    
    { {     319}, {  19} }, // be           
    { {     320}, {  20} }, // ki           
    { {     321}, {  21} }, // elagazas     
    { {     322}, {  22} }, // ciklus       
    { {     276}, {  23} }, // AZONOSITO    
    { {     269}, {  24} }, // BE           
    { {     270}, {  25} }, // KI           
    { {     262}, {  26} }, // HA           
    { {     266}, {  27} }, // CIKLUS       
    { {       0}, { -12} },                 
};

SR__ s_66[] =
{
    { { REQ_DEF}, {   4} },           
    { {     292}, {  52} }, // SZORZAS
    { {     293}, {  53} }, // OSZTAS 
    { {     294}, {  54} }, // MARADEK
    { {       0}, { -33} },           
};

SR__ s_67[] =
{
    { { REQ_DEF}, {   4} },           
    { {     292}, {  52} }, // SZORZAS
    { {     293}, {  53} }, // OSZTAS 
    { {     294}, {  54} }, // MARADEK
    { {       0}, { -34} },           
};

SR__ s_68[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_69[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_70[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_71[] =
{
    { { REQ_DEF}, {   6} },           
    { {     290}, {  50} }, // PLUSZ  
    { {     291}, {  51} }, // MINUSZ 
    { {     292}, {  52} }, // SZORZAS
    { {     293}, {  53} }, // OSZTAS 
    { {     294}, {  54} }, // MARADEK
    { {       0}, { -38} },           
};

SR__ s_72[] =
{
    { { REQ_DEF}, {   6} },           
    { {     290}, {  50} }, // PLUSZ  
    { {     291}, {  51} }, // MINUSZ 
    { {     292}, {  52} }, // SZORZAS
    { {     293}, {  53} }, // OSZTAS 
    { {     294}, {  54} }, // MARADEK
    { {       0}, { -39} },           
};

SR__ s_73[] =
{
    { { REQ_DEF}, {   8} },           
    { {     290}, {  50} }, // PLUSZ  
    { {     291}, {  51} }, // MINUSZ 
    { {     292}, {  52} }, // SZORZAS
    { {     293}, {  53} }, // OSZTAS 
    { {     294}, {  54} }, // MARADEK
    { {     288}, {  55} }, // KISEBB 
    { {     289}, {  56} }, // NAGYOBB
    { {       0}, { -40} },           
};

SR__ s_74[] =
{
    { { REQ_DEF}, {   9} },           
    { {     290}, {  50} }, // PLUSZ  
    { {     291}, {  51} }, // MINUSZ 
    { {     292}, {  52} }, // SZORZAS
    { {     293}, {  53} }, // OSZTAS 
    { {     294}, {  54} }, // MARADEK
    { {     288}, {  55} }, // KISEBB 
    { {     289}, {  56} }, // NAGYOBB
    { {     287}, {  57} }, // EGYENLO
    { {       0}, { -41} },           
};

SR__ s_75[] =
{
    { { REQ_DEF}, {  10} },           
    { {     290}, {  50} }, // PLUSZ  
    { {     291}, {  51} }, // MINUSZ 
    { {     292}, {  52} }, // SZORZAS
    { {     293}, {  53} }, // OSZTAS 
    { {     294}, {  54} }, // MARADEK
    { {     288}, {  55} }, // KISEBB 
    { {     289}, {  56} }, // NAGYOBB
    { {     287}, {  57} }, // EGYENLO
    { {     285}, {  58} }, // ES     
    { {       0}, { -42} },           
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, { 12} },               
    { {       275}, { 81} }, // JOBBZAROJEL
    { {       290}, { 50} }, // PLUSZ      
    { {       291}, { 51} }, // MINUSZ     
    { {       292}, { 52} }, // SZORZAS    
    { {       293}, { 53} }, // OSZTAS     
    { {       294}, { 54} }, // MARADEK    
    { {       288}, { 55} }, // KISEBB     
    { {       289}, { 56} }, // NAGYOBB    
    { {       287}, { 57} }, // EGYENLO    
    { {       285}, { 58} }, // ES         
    { {       284}, { 59} }, // VAGY       
    { {         0}, {  0} },               
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, { 12} },               
    { {       275}, { 82} }, // JOBBZAROJEL
    { {       290}, { 50} }, // PLUSZ      
    { {       291}, { 51} }, // MINUSZ     
    { {       292}, { 52} }, // SZORZAS    
    { {       293}, { 53} }, // OSZTAS     
    { {       294}, { 54} }, // MARADEK    
    { {       288}, { 55} }, // KISEBB     
    { {       289}, { 56} }, // NAGYOBB    
    { {       287}, { 57} }, // EGYENLO    
    { {       285}, { 58} }, // ES         
    { {       284}, { 59} }, // VAGY       
    { {         0}, {  0} },               
};

SR__ s_78[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, {  3} },            
    { {       265}, { 83} }, // HA_VEGE 
    { {       264}, { 84} }, // KULONBEN
    { {         0}, {  0} },            
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       268}, { 85} }, // CIKLUS_VEGE
    { {         0}, {  0} },               
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_82[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_84[] =
{
    { { REQ_DEF}, {  14} },                 
    { {     316}, {  86} }, // utasitaslista
    { {     317}, {  33} }, // utasitas     
    { {     279}, {  17} }, // SKIP         
    { {     318}, {  18} }, // ertekadas    
    { {     319}, {  19} }, // be           
    { {     320}, {  20} }, // ki           
    { {     321}, {  21} }, // elagazas     
    { {     322}, {  22} }, // ciklus       
    { {     276}, {  23} }, // AZONOSITO    
    { {     269}, {  24} }, // BE           
    { {     270}, {  25} }, // KI           
    { {     262}, {  26} }, // HA           
    { {     266}, {  27} }, // CIKLUS       
    { {       0}, { -12} },                 
};

SR__ s_85[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_86[] =
{
    { { REQ_TOKEN}, {  2} },           
    { {       265}, { 87} }, // HA_VEGE
    { {         0}, {  0} },           
};

SR__ s_87[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 68 "plang--.y"
        {
         std::cout << d_vsp__[-3].utasitas->kod + d_vsp__[-2].utasitas->kod + d_vsp__[-1].utasitas->kod + d_vsp__[0].utasitas->kod;
         delete d_vsp__[-3].utasitas;
         delete d_vsp__[-2].utasitas;
         delete d_vsp__[-1].utasitas;
         delete d_vsp__[0].utasitas;
         }
        break;

        case 2:
#line 79 "plang--.y"
        {
         d_val__.utasitas = new utasitas_leiro( 0, 
         std::string("extern be_egesz\n") + "extern be_logikai\n"
         + "extern ki_egesz\n" + "extern ki_logikai\n"
         + "global main\n" );
         }
        break;

        case 3:
#line 89 "plang--.y"
        {
         d_val__.utasitas = new utasitas_leiro( d_loc__.first_line, "ret\n" );
         }
        break;

        case 4:
#line 96 "plang--.y"
        {
         d_val__.utasitas = new utasitas_leiro( 0, "" );
         }
        break;

        case 5:
#line 101 "plang--.y"
        {
         d_val__.utasitas = new utasitas_leiro( d_loc__.first_line, 
         "section .bss\n" + d_vsp__[0].utasitas->kod );
         delete d_vsp__[0].utasitas;
         }
        break;

        case 7:
#line 112 "plang--.y"
        {
         d_val__.utasitas = new utasitas_leiro( d_vsp__[-1].utasitas->sor, d_vsp__[-1].utasitas->kod + d_vsp__[0].utasitas->kod );
         delete d_vsp__[-1].utasitas;
         delete d_vsp__[0].utasitas;
         }
        break;

        case 8:
#line 121 "plang--.y"
        {
         if( szimb_tabla.count(*d_vsp__[0].szoveg) > 0 )
         {
         std::cerr << d_loc__.first_line << ": A(z) '" << *d_vsp__[0].szoveg << "' valtozo mar definialva volt a "
         << szimb_tabla[*d_vsp__[0].szoveg].def_sora << ". sorban." << std::endl;
         exit(1);
         }
         else
         {
         szimb_tabla[*d_vsp__[0].szoveg] = valtozo_leiro(d_loc__.first_line,Egesz,sorszam++);
         d_val__.utasitas = new utasitas_leiro( d_loc__.first_line, 
         szimb_tabla[*d_vsp__[0].szoveg].cimke + " resb 4\n" );
         }
         delete d_vsp__[0].szoveg;
         }
        break;

        case 9:
#line 138 "plang--.y"
        {
         if( szimb_tabla.count(*d_vsp__[0].szoveg) > 0 )
         {
         std::cerr << d_loc__.first_line << ": A(z) '" << *d_vsp__[0].szoveg << "' valtozo mar definialva volt a "
         << szimb_tabla[*d_vsp__[0].szoveg].def_sora << ". sorban." << std::endl;
         exit(1);
         }
         else
         {
         szimb_tabla[*d_vsp__[0].szoveg] = valtozo_leiro(d_loc__.first_line,Logikai,sorszam++);
         d_val__.utasitas = new utasitas_leiro( d_loc__.first_line, 
         szimb_tabla[*d_vsp__[0].szoveg].cimke + " resb 1\n" );
         }
         delete d_vsp__[0].szoveg;
         }
        break;

        case 10:
#line 155 "plang--.y"
        {
         if( szimb_tabla.count(*d_vsp__[0].szoveg) > 0 )
         {
         std::cerr << d_loc__.first_line << ": A(z) '" << *d_vsp__[0].szoveg << "' valtozo mar definialva volt a "
         << szimb_tabla[*d_vsp__[0].szoveg].def_sora << ". sorban." << std::endl;
         exit(1);
         }
         else
         {
         szimb_tabla[*d_vsp__[0].szoveg] = valtozo_leiro(d_loc__.first_line, Ido_t,sorszam++);
         d_val__.utasitas = new utasitas_leiro( d_loc__.first_line, 
         szimb_tabla[*d_vsp__[0].szoveg].cimke + " resb 1\n" );
         }
         delete d_vsp__[0].szoveg; 
         }
        break;

        case 11:
#line 174 "plang--.y"
        {
         d_val__.utasitas = new utasitas_leiro( d_loc__.first_line,
         std::string("section .text\n") + "main:\n" + d_vsp__[-1].utasitas->kod + d_vsp__[0].utasitas->kod );
         delete d_vsp__[-1].utasitas;
         delete d_vsp__[0].utasitas;
         }
        break;

        case 12:
#line 184 "plang--.y"
        {
         d_val__.utasitas = new utasitas_leiro( d_loc__.first_line, "" );
         }
        break;

        case 13:
#line 189 "plang--.y"
        {
         d_val__.utasitas = new utasitas_leiro( d_vsp__[-1].utasitas->sor, d_vsp__[-1].utasitas->kod + d_vsp__[0].utasitas->kod );
         delete d_vsp__[-1].utasitas;
         delete d_vsp__[0].utasitas;
         }
        break;

        case 14:
#line 198 "plang--.y"
        {
         d_val__.utasitas = new utasitas_leiro( d_loc__.first_line, "" );
         }
        break;

        case 20:
#line 215 "plang--.y"
        {
         if( szimb_tabla.count( *d_vsp__[-2].szoveg ) == 0 )
         {
         std::cerr << d_loc__.first_line << ": A(z) '" << *d_vsp__[-2].szoveg << "' valtozo nincs deklaralva." << std::endl;
         exit(1);
         }
         else if( szimb_tabla[*d_vsp__[-2].szoveg].vtip != d_vsp__[0].kif->ktip )
         {
         std::cerr << d_loc__.first_line << ": Az ertekadas jobb- es baloldalan kulonbozo tipusu kifejezesek allnak." << std::endl;
         exit(1);
         }
         else
         {
         std::string reg;
         if( d_vsp__[0].kif->ktip == Egesz )
         reg = "eax";
         else if ( d_vsp__[0].kif->ktip == Logikai)
         reg = "al";
         else
         reg = "";
         d_val__.utasitas = new utasitas_leiro( d_loc__.first_line,
         d_vsp__[0].kif->kod + "mov " + "[" + szimb_tabla[*d_vsp__[-2].szoveg].cimke + "]," + reg + "\n" );
         }
         delete d_vsp__[0].kif;
         }
        break;

        case 21:
#line 244 "plang--.y"
        {
         if( szimb_tabla.count( *d_vsp__[0].szoveg ) == 0 )
         {
         std::cerr << d_loc__.first_line << ": A(z) '" << *d_vsp__[0].szoveg << "' valtozo nincs deklaralva." << std::endl;
         exit(1);
         }
         else
         {
         std::string muvelet, reg;
         if( szimb_tabla[*d_vsp__[0].szoveg].vtip == Egesz )
         {
         muvelet = "be_egesz";
         reg = "eax";
         }
         else
         {
         muvelet = "be_logikai";
         reg = "al";
         }
         d_val__.utasitas = new utasitas_leiro( d_loc__.first_line,
         "call " + muvelet + "\n" + "mov [" + szimb_tabla[*d_vsp__[0].szoveg].cimke + "]," + reg + "\n" );
         }
         delete d_vsp__[0].szoveg;
         }
        break;

        case 22:
#line 272 "plang--.y"
        {
         std::string muvelet;
         if( d_vsp__[0].kif->ktip == Egesz )
         muvelet = "ki_egesz";
         else
         muvelet = "ki_logikai";
         d_val__.utasitas = new utasitas_leiro( d_loc__.first_line, d_vsp__[0].kif->kod + "push eax\n" + "call " + muvelet + "\n" + "pop eax\n" );
         delete d_vsp__[0].kif;
         }
        break;

        case 23:
#line 285 "plang--.y"
        {
         if( d_vsp__[-3].kif->ktip != Logikai )
         {
         std::cerr << d_loc__.first_line << ": Nem logikai tipusu az elagazas feltetele." << std::endl;
         exit(1);
         }
         else
         {
         std::stringstream out1;
         out1 << "Cimke" << Parser::sorszam++;
         std::string then = out1.str();
         std::stringstream out2;
         out2 << "Cimke" << Parser::sorszam++;
         std::string end = out2.str();
         d_val__.utasitas = new utasitas_leiro( d_vsp__[-3].kif->sor, 
         d_vsp__[-3].kif->kod + "cmp al,1\n" + "je " + then + "\n" + "jmp " + end + "\n"
         + then + ":\n" + d_vsp__[-1].utasitas->kod + end + ":\n" );
         }
         delete d_vsp__[-3].kif;
         delete d_vsp__[-1].utasitas;
         }
        break;

        case 24:
#line 308 "plang--.y"
        {
         if( d_vsp__[-5].kif->ktip != Logikai )
         {
         std::cerr << d_loc__.first_line << ": Nem logikai tipusu az elagazas feltetele." << std::endl;
         exit(1);
         }
         else
         {
         std::stringstream out1;
         out1 << "Cimke" << Parser::sorszam++;
         std::string then = out1.str();
         std::stringstream out2;
         out2 << "Cimke" << Parser::sorszam++;
         std::string elsec = out2.str();
         std::stringstream out3;
         out3 << "Cimke" << Parser::sorszam++;
         std::string end = out3.str();
         d_val__.utasitas = new utasitas_leiro( d_vsp__[-5].kif->sor, 
         d_vsp__[-5].kif->kod + "cmp al,1\n" + "je " + then + "\n" + "jmp " + elsec + "\n"
         + then + ":\n" + d_vsp__[-3].utasitas->kod + "jmp " + end + "\n" + elsec + ":\n"
         + d_vsp__[-1].utasitas->kod + end + ":\n" );
         }
         delete d_vsp__[-5].kif;
         delete d_vsp__[-3].utasitas;
         delete d_vsp__[-1].utasitas;
         }
        break;

        case 25:
#line 338 "plang--.y"
        {
         if( d_vsp__[-2].kif->ktip != Logikai )
         {
         std::cerr << d_loc__.first_line << ": Nem logikai tipusu a ciklus feltetele." << std::endl;
         exit(1);
         }
         else
         {
         std::stringstream out1;
         out1 << "Cimke" << Parser::sorszam++;
         std::string eleje = out1.str();
         std::stringstream out2;
         out2 << "Cimke" << Parser::sorszam++;
         std::string mag = out2.str();
         std::stringstream out3;
         out3 << "Cimke" << Parser::sorszam++;
         std::string end = out3.str();
         d_val__.utasitas = new utasitas_leiro( d_vsp__[-2].kif->sor, eleje + ":\n"
         + d_vsp__[-2].kif->kod + "cmp al,1\n" + "je " + mag + "\n" + "jmp " + end + "\n"
         + mag + ":\n" + d_vsp__[-1].utasitas->kod + "jmp " + eleje + "\n" + end + ":\n" );
         }
         delete d_vsp__[-2].kif;
         delete d_vsp__[-1].utasitas;
         }
        break;

        case 26:
#line 366 "plang--.y"
        {
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz, "mov eax," + *d_vsp__[0].szoveg + "\n");
         delete d_vsp__[0].szoveg;
         }
        break;

        case 27:
#line 372 "plang--.y"
        {
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai, "mov al,1\n" );
         }
        break;

        case 28:
#line 377 "plang--.y"
        {
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai, "mov al,0\n" );
         }
        break;

        case 29:
#line 382 "plang--.y"
        {
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Ido_t, "mov al,0\n" );
         }
        break;

        case 30:
#line 387 "plang--.y"
        {
         if( szimb_tabla.count( *d_vsp__[0].szoveg ) == 0 )
         {
         std::cerr << d_loc__.first_line << ": A(z) '" << *d_vsp__[0].szoveg << "' valtozo nincs deklaralva." << std::endl;
         exit(1);
         }
         else
         {
         valtozo_leiro vl = szimb_tabla[*d_vsp__[0].szoveg];
         std::string reg;
         if( vl.vtip == Egesz )
         reg = "eax";
         else
         reg = "al";
         d_val__.kif = new kifejezes_leiro( vl.def_sora, vl.vtip, "mov " + reg + ",[" + vl.cimke + "]\n" );
         delete d_vsp__[0].szoveg;
         }
         }
        break;

        case 31:
#line 408 "plang--.y"
        {
         if( d_vsp__[-1].kif->ktip != Ido_t)
         {
         std::cerr << d_vsp__[-1].kif->sor << ": Az ora függvény nem ido tipus-al lett meghivva." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz, "");
         delete d_vsp__[-1].kif;
         }
        break;

        case 32:
#line 420 "plang--.y"
        {
         if( d_vsp__[-1].kif->ktip != Ido_t)
         {
         std::cerr << d_vsp__[-1].kif->sor << ": A perc függvény nem ido tipus-al lett meghivva." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz, ""); 
         delete d_vsp__[-1].kif;
         }
        break;

        case 33:
#line 431 "plang--.y"
        {
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": A '+' operator baloldalan nem egesz tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A '+' operator jobboldalan nem egesz tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz, d_vsp__[0].kif->kod + "push eax\n" + d_vsp__[-2].kif->kod + "pop ebx\n" + "add eax,ebx\n" );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 34:
#line 448 "plang--.y"
        {
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": A '-' operator baloldalan nem egesz tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A '-' operator jobboldalan nem egesz tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz, d_vsp__[0].kif->kod + "push eax\n" + d_vsp__[-2].kif->kod + "pop ebx\n" + "sub eax,ebx\n" );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 35:
#line 465 "plang--.y"
        {
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": A '*' operator baloldalan nem egesz tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A '*' operator jobboldalan nem egesz tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz, d_vsp__[0].kif->kod + "push eax\n" + d_vsp__[-2].kif->kod + "pop ebx\n" + "mov edx,0\n" + "mul ebx\n" );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 36:
#line 482 "plang--.y"
        {
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": A '/' operator baloldalan nem egesz tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A '/' operator jobboldalan nem egesz tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz, d_vsp__[0].kif->kod + "push eax\n" + d_vsp__[-2].kif->kod + "pop ebx\n" + "mov edx,0\n" + "div ebx\n" );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 37:
#line 499 "plang--.y"
        {
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": A '%' operator baloldalan nem egesz tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A '%' operator jobboldalan nem egesz tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz, d_vsp__[0].kif->kod + "push eax\n" + d_vsp__[-2].kif->kod + "pop ebx\n" + "mov edx,0\n" + "div ebx\n" + "mov eax,edx\n" );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 38:
#line 516 "plang--.y"
        {
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": A '<' operator baloldalan nem egesz tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A '<' operator jobboldalan nem egesz tipusu kifejezes all." << std::endl;
         exit(1);
         }
         std::stringstream out;
         out << "Cimke" << Parser::sorszam++;
         std::string cimke = out.str();
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai,
         d_vsp__[0].kif->kod + "push eax\n" + d_vsp__[-2].kif->kod + "pop ebx\n"
         + "cmp eax,ebx\n" + "mov al,1\n" + "jb " + cimke + "\n"
         + "mov al,0\n" + cimke + ":\n" );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 39:
#line 539 "plang--.y"
        {
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": A '>' operator baloldalan nem egesz tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A '>' operator jobboldalan nem egesz tipusu kifejezes all." << std::endl;
         exit(1);
         }
         std::stringstream out;
         out << "Cimke" << Parser::sorszam++;
         std::string cimke = out.str();
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai,
         d_vsp__[0].kif->kod + "push eax\n" + d_vsp__[-2].kif->kod + "pop ebx\n"
         + "cmp eax,ebx\n" + "mov al,1\n" + "ja " + cimke + "\n"
         + "mov al,0\n" + cimke + ":\n" );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 40:
#line 562 "plang--.y"
        {
         if( d_vsp__[-2].kif->ktip != d_vsp__[0].kif->ktip )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": Az '=' operator jobb- es baloldalan kulonbozo tipusu kifejezesek allnak." << std::endl;
         exit(1);
         }
         std::stringstream out;
         out << "Cimke" << Parser::sorszam++;
         std::string cimke = out.str();
         std::string reg1,reg2;
         if( d_vsp__[-2].kif->ktip == Egesz )
         {
         reg1 = "eax";
         reg2 = "ebx";
         }
         else
         {
         reg1 = "al";
         reg2 = "bl";
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai,
         d_vsp__[0].kif->kod + "push eax\n" + d_vsp__[-2].kif->kod + "pop ebx\n"
         + "cmp " + reg1 + "," + reg2 + "\n" + "mov al,1\n" + "je " + cimke + "\n"
         + "mov al,0\n" + cimke + ":\n" );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 41:
#line 591 "plang--.y"
        {
         if( d_vsp__[-2].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": Az 'ES' operator baloldalan nem logikai tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[0].kif->sor << ": Az 'ES' operator jobboldalan nem logikai tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai,
         d_vsp__[0].kif->kod + "push eax\n" + d_vsp__[-2].kif->kod + "pop ebx\n" + "and al,bl\n" );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 42:
#line 609 "plang--.y"
        {
         if( d_vsp__[-2].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": A 'VAGY' operator baloldalan nem logikai tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A 'VAGY' operator jobboldalan nem logikai tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai,
         d_vsp__[0].kif->kod + "push eax\n" + d_vsp__[-2].kif->kod + "pop ebx\n" + "or al,bl\n" );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 43:
#line 627 "plang--.y"
        {
         if( d_vsp__[0].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A 'NEM' operator utan nem logikai tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai,
         d_vsp__[0].kif->kod + "xor al,1\n" );
         delete d_vsp__[0].kif;
         }
        break;

        case 44:
#line 639 "plang--.y"
        {
         d_val__.kif = d_vsp__[-1].kif;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



